.PHONY: clean All

All:
	@echo "----------Building project:[ ARC102A - Debug ]----------"
	@cd "ARC102A" && "$(MAKE)" -f  "ARC102A.mk"
clean:
	@echo "----------Cleaning project:[ ARC102A - Debug ]----------"
	@cd "ARC102A" && "$(MAKE)" -f  "ARC102A.mk" clean
